BaSP-m2023/nai-megarocket-server

src/controllers/super-admins.js

Changed the function to async to correctly functionality, now if you create a new super admin with an existing email gives you error but don't break the console and the app.

BaSP-MR-23: HOTFIX Super Admin, post.

---

src/controllers/member.js

Fixed members put by moving the .then() to the line 169

BaSP-MR-18: HotFix Members put 

---

src/controllers/class.js
src/models/class.js
src/validations/class.js

Added id references on class to trainer and activity in clasess model 
Added .populate to getAllClasses in classes controller to show it works
Added .populate to getClassId classes controller to show it works
Changed the validation from string to an idObject of trainers and activitys in clasess joi validation

BaSP - MR-41: ID references on Class

---

src/controllers/activity.js

Fixed delete endpoint on activity controller

BaSP - MR-20:HotFix-Activity-Delete

---

jest.setup.js
package-lock.json

Mistake on mongo options configuration.
`useNewUrlParse => useNewUrlParser`

BaSP-MR-44: HotFix setup configuration

---

src/controllers/subscription.js
src/models/subscription.js

Added reference to members by id in subscription model.
Added reference to class by id in subscription model.
Added populate() in getAll and getById endpoints.

BaSP-MR-42: Subscriptions id references 

---

src/controllers/trainer.js
src/validations/trainer.js

App crash fixed in Trainers update controller. Returns added to the res.status.json.

BaSP-MR-25: Hotfix Trainers put

---

src/controllers/activity.js
src/validations/activity.js

In update function, there were added return's to activity controllers and validations.
Now when updating an activity with an invalid Id format, it returns a message: 'invalid id format'.
And the App does not crash any more.

BaSP - MR-21: HotFix - Activity/Put

---

src/controllers/trainer.js

Fixed bug on delete method that crashed the app.
Problem:  the app were sending two responses at the same time.

BaSP-MR-24: HotFix Trainers delete

---

jest.setup.js
src/controllers/super-admins.js
src/seeds/super-admins.js
src/tests/super-admins.test.js

Added seed for super admins
Added test for PUT endpoint
Added test for DEL endpoint

BaSP-MR-38: Test super admins put delete

---

jest.setup.js
src/controllers/admins.js
src/seeds/admins.js
src/tests/admins.test.js

Added seed for admins
Added test for admins Get, getById and Post

BaSP-MR-29:Test admin Get GetById Post

---

Readme.md

Updated information was added to Readme file.

BaSP-MR-43: Readme  / Week-10

---

src/controllers/activity.js
src/validations/super-admins.js

Fixed isActive to be recognized as a change when modified from PUT.

BaSP-MR-173: Fixed isActive 

---

.husky/pre-commit
jest.setup.js
src/controllers/auth.js

Added authentication logic for the entities of:
* Admin
* Member

BaSP-MR-199: Auth controllers logic members and admin

---

src/middlewares/authMiddleware.js

- Make the middleware (server) to parse the token and check the role.

BaSP-MR-197: Middleware logic

---

src/helper/firebase/index.js

We were having trouble with the PRIVATE_KEY in the deploy of vercel and we need to fix it.

BaSP-HOTFIX-MR-203: hotfix private key

---

src/controllers/super-admins.js
src/controllers/trainer.js
src/middlewares/adminMemberMiddleware.js
src/middlewares/adminMiddleware.js
src/middlewares/adminTrainerMemberMiddleware.js
src/middlewares/adminTrainerMiddleware.js
src/middlewares/memberMiddleware.js
src/middlewares/superAdminMiddleware.js
src/routes/activity.js
src/routes/admins.js
src/routes/auth.js
src/routes/class.js
src/routes/index.js
src/routes/member.js
src/routes/subscription.js
src/routes/super-admins.js
src/routes/trainer.js

In this pull request, we're adding security to our application. We've added private routes to the existing endpoints in our code to improve the security and control over who can access certain functionalities.
Changes made:
• Created middlewares to check the role of the different tokens received.
• Add those middlewares in the routes of each entity (following the business logic).

BaSP-MR-206: Added private routes

---

src/controllers/auth.js
src/routes/member.js
src/routes/subscription.js

Added permissions in authMiddleware for trainers.

BaSP-MR-220: Added permissions auth trainers.

---

src/controllers/class.js
src/controllers/subscription.js
src/models/member.js
src/models/subscription.js
src/routes/auth.js
src/validations/subscription.js

This PR introduces updates to the subscription and member controllers/models to enhance functionality and improve user management.
Subscription Updates:
• Added a new field, "isActive," to the subscription models and controllers
Member Updates:
• Modified the default value of the "isActive" field for new members to be set to false. This change ensures that newly created member accounts are inactive by default, requiring an admin to manually activate them by setting their "isActive" status to true.
Classes Controller Update:
• Implemented a fix in the class controller to prevent scheduling conflicts. The controller now checks for the existence of a class on the same day and hour before allowing the creation of a new class.

BaSP-MR-226: update sub member

---

src/routes/subscription.js

Modified permission auth update suscription in route suscription.

BaSP-MR-236: Modified permission auth update suscription

---

src/controllers/class.js
src/controllers/subscription.js
src/models/class.js
src/models/member.js
src/models/trainer.js

In this PR I implemented timestamps in trainers and members models, and also populate subscriptions into classes.

BaSP-MR-252: feat timestamps and populate subs in classes

---

src/controllers/class.js

Fix member populate in classes

BaSP-HOTFIX-MR-282: fix populate in classes
